import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/navbar/Navbar";
import AuthProvider from "@/components/auth/AuthProvider";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body className={`bg-[#0d0c22] ${inter.className} text-white`}>
        {/* <div >
          <Navbar></Navbar>
        </div> */}
      {/* <div className="flex">
      <div className="mt-[-110px] ">
        <Sidebar></Sidebar>
      </div>
       <div >  */}
       <AuthProvider>{children}</AuthProvider>
       {/* </div>
      </div> */}
       <Toaster />
       </body>
    </html>
  );
}

